import react from "react";
import { ReactDOM } from "react";
import App

const index = () => {

  return (
    <div>
      <Head>
        <title>Schedir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Hero/>
      {/* <Boat/> */}
        <Main/>
        {/* <SectionsLink/> */}
    </div>
  );
};

export default index;