import React from 'react';
import ReactDOM from "react-dom";
import { BrowserRouter as Router } from "react-router-dom";
import MyApp from "./_app";

// const Index = () => {

//   return (
//     <div>
//       <Head>
//         <title>Schedir</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="" />
//       </Head>
//       <Hero/>
//       <Main/>
//     </div>
//   );
// };

// export default Index;

// ReactDOM.render(
//     <Router>
//       <React.StrictMode>
//         <MyApp/>
//       </React.StrictMode>
//     </Router>,
//   document.getElementById("root")
// );

import ReactDOM from 'react-dom';

if (typeof window !== 'undefined') {
    ReactDOM.render(<Index />, document.getElementById("root"));
}