import React from 'react';
import ReactDOM from "react-dom";
import { BrowserRouter as Router } from "react-router-dom";
import MyApp from "./_app";

// const Index = () => {

//   return (
//     <div>
//       <Head>
//         <title>Schedir</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="" />
//       </Head>
//       <Hero/>
//       <Main/>
//     </div>
//   );
// };

// export default Index;

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);