import Head from 'next/head';
import Hero from '../components/Home/Hero';
import Main from '../components/Home/Main';
import {motion} from 'framer-motion'

const Index = () => {

  return (
    <motion.div>
      <Head>
        <title>Schedir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <Hero/>
      <Main/>
    </div>
  );
};

export default Index;