import Head from 'next/head';
import { Router } from 'react-router-dom';
import Hero from '../components/Home/Hero';
import Main from '../components/Home/Main';

const Index = () => {

  return (
    <div>
      <Head>
        <title>Schedir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Router>
        
      </Router>
    </div>
  );
};

export default Index;