
import React from 'react'
import Head from 'next/head';
import {motion} from 'framer-motion'
import Joinpanel from '../components/Join/Joinpanel';

const Join = () => {
  return (
    <motion.div>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        <div href="#" className="fixed items-center my-auto ml-20 ">
                    <img src="/HomeMedia/posidonia_logo.png" className="h-28 mt-0 ml-5" alt="Schedir Logo" />
                </div>
        <div className='bg-schedir-blue bg-cover'>
          <Joinpanel/>
        </div>
    </motion.div>
  )
}

export default Join;