
import React from 'react'
import Head from 'next/head';
import {motion} from 'framer-motion'
import Joinpanel from '../components/Join/Joinpanel';

const Join = () => {
  return (
    <motion.div>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        <div className='bg-'>

        </div>
        <Joinpanel/>
    </motion.div>
  )
}

export default Join;