import React from 'react'
import Head from 'next/head';
import Timeline from '../components/Logbook/Timeline';
import Date from '../components/Logbook/Date';

const Logbook = () => {
  return (
    <div>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        <Timeline/>
    </div>
  )
}

export default Logbook