import React from 'react'
import Head from 'next/head';
import Timeline from '../components/Logbook/Timeline';
import {motion} from 'framer-motion'

const Logbook = () => {
  return (
    <motion.div
    initial={{ x: -100, opacity: 0 }}
    animate={{ x: 0, opacity: 1 }}
    exit={{x:100, opacity:1}}
    transition={{
      duration: 0.5,
    }}>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        <Timeline/>
    </motion.div>
  )
}

export default Logbook