import React from 'react'
import Head from 'next/head';
import Timeline from '../components/LoTimeline';
import NavBar2 from '../components/Logbook/NavBar2';

const logbook = () => {
  return (
    <div>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        <NavBar2/>
        <Timeline/>
    </div>
  )
}

export default logbook