import React from 'react'
import Head from 'next/head';
import {motion} from 'framer-motion'
import Route from '../components/TheRoute/Route';

const Route = () => {
  return (
    <motion.div
    initial={{ x: 1500, opacity: 1 }}
    animate={{ x: 0, opacity: 1 }}
    exit={{x:-1500, opacity:1}}
    transition={{
      duration: 1,
    }}>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        {/* <Route/> */}
    </motion.div>
  )
}

export default Route