import React from 'react'
import Head from 'next/head';
import {motion} from 'framer-motion'
import RouteMap from '../components/TheRoute/RouteMap';

const Route = () => {
  return (
    <motion.div
    initial={{ x: 1500, opacity: 1 }}
    animate={{ x: 0, opacity: 1 }}
    exit={{x:-1500, opacity:1}}
    transition={{
      duration: 1,
    }}>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        <RouteMap 
          box={"[30.42%] [18.52%] [38.54%] 1556"}/>
        <RouteMap 
          box={"0 0 3770 1556"}/>
    </motion.div>
  )
}

export default Route