import React from 'react'
import Head from 'next/head';
import Blueprint from '../components/TheSchedirComps/Blueprint';
import { motion, useScroll, useTransform, useSpring} from 'framer-motion'

const TheSchedir = () => {

  return (
    <motion.div>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>          
        <Blueprint/>
  
    </motion.div>
  )
}

export default TheSchedir;