import React from 'react'
import Head from 'next/head';
import {motion} from 'framer-motion'
import Blueprint from '../components/TheSchedirComps/Blueprint';
import Schedir_1 from '../components/TheSchedirComps/Schedir_1';

const TheSchedir = () => {
  return (
    <motion.div
    initial={{ x: 1500, opacity: 1 }}
    animate={{ x: 0, opacity: 1 }}
    exit={{x:-1500, opacity:1}}
    transition={{
      duration: 1,
    }}>
        <Head>
          <title>Schedir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>
        <div className='relative'>
          <div className='flex justify-center'>
            <div className='absolute z-[10]'>
              <h1 className='text-transparent font-bold bg-clip-text bg-gradient-to-r from-schedir-green to-schedir-red2 md:text-[80px] hover:from-schedir-red2 hover:to-schedir-green'>
                The Schedir
              </h1>
            </div>
          </div>
          <Blueprint/>

          {/* <Schedir_1/> */}
        </div>
    </motion.div>
  )
}

export default TheSchedir